repos:
# BASIC CONF FOR ALL PRE-COMMITS REPO TYPE
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: no-commit-to-branch
      args:
      - --branch
      - main
      - --branch
      - dev
      - --branch
      - staging
      - --branch
      - qa
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-yaml
      args:
      - '--allow-multiple-documents'
    - id: check-json
    - id: check-shebang-scripts-are-executable

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
    - id: conventional-pre-commit

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
    - id: gitleaks

# SPECIFIC CONF FOR TERRAFORM MODULE REPOSITORIES
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
    - id: terraform_fmt
      args:
      - --args=-diff
      - --args=-write=true
    - id: terraform_docs
    - id: terraform_tflint
      files: \.tf$
      args:
      - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
      - --args=--call-module-type=all
      - --args=--recursive
    - id: terraform_validate
      args:
      - --tf-init-args=-backend=false

  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: v0.19.0
  #   hooks:
  #     - id: terraform-docs-go
  #       args: ["-c", ".terraform-docs.yaml", "terraform/lab-0-terraform"]
