formatter: markdown table

content: ""

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
    {{- printf "\n" -}}

output-values:
  enabled: false
  from: ""

recursive:
  enabled: true
  include-main: true
  path: ../modules
  mode: replace

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 4
  lockfile: true
  required: true
  sensitive: true
  type: true
